### ISSUE TITLE
Feature: Login

### ISSUE THREAD

**Issue by schefDev** [dfensgmbh/biz.dfch.CS.Activiti.Client#1]
# FUNCTION Name: Login
PARAMETERS
	string HostUri  // http://localhost:8080/activiti-rest/service/
	string Username
	string Password
	NetworkCredential Credentials
	
# Test Cases
 * [x] **Login (Success)**
```
GIVEN 
	Client is not connected
        AND activiti server is available
WHEN 
	Call function Login with correct parameters
THEN
	Client is connected and logged in
```

  * [x] **Login with wrong credentials**
```
GIVEN
       Client is not connected
       AND activiti server is available
WHEN
       Call function Login with wrong credentials
THEN
       Client get an exception
```

  * [x] **Login to non active server/wrong server name**
```
GIVEN
	Client is not connected
	AND activiti server is not available
WHEN
	Call function Login
THEN
	Client get an exception
```

**Comment by dfch** [comment]
@schefDev cool that you started documenting test cases before coding! - you are on your way to become a real TDD developer!

Regarding the suggested parameter I would like to note the following:

Conceptually a client will call the library similar to this:
``` csharp
var client = new biz.dfch.CS.Activiti.Client(...);
client.login(...);
```

Therefore I suggest, to have a constructor that already accepts `HostUri` and credentials (among a parameterless constructor). These properties should be saved into public properties of the client. So a `login()` could optionally accept credentials as well (or use the already supplied properties).
This will allow much greater flexibility.

Therefore the client might look like this:
``` csharp
namespace biz.dfch.CS.Activiti
{

public class Client
{
  public Uri Server { get; set; }
  public string Username { get; set; }
  public string Password { set; }
  public string SessionId { get; }
  public Client()
  {
    // ...
  }
  public Client(Uri Server, string Username, string Password)
  {
    // ...
    this.Username = Username;
    // ...
  }
  string Login()
  {
    // return session id
  }
  string Login(string Username, string Password)
  {
    // set user and pass
    // return session id
  }
}

}
```

Do you know what I mean?
