### ISSUE TITLE
Test results must be published to Jira

### ISSUE THREAD

**Issue by trumpetchris** [dfensgmbh/biz.dfch.CS.Activiti.Client#13]

**Comment by dfch** [comment]
@trumpetchris check with @gaestu on how to do this and where to publish

**Comment by trumpetchris** [comment]
Inserted the Project to issue.swisscom.ch and added the necessary tag in the tests.
The next time the tests are deployed we will see if the test results are in Jira.

**Comment by trumpetchris** [comment]
Added further tests for every context.

**Comment by dfch** [comment]
@trumpetchris when referring to *further tests" it is helpful to at least reference the commit hash (if you did not reference the issue via the issue)

**Comment by trumpetchris** [comment]
Repo is included in the tests and test results are published in Jira.
