### ISSUE TITLE
# FUNCTION Name: Get Workflow Definition By id

### ISSUE THREAD

**Issue by trumpetchris** [dfensgmbh/biz.dfch.CS.Activiti.Client#14]
# FUNCTION Name: Get Workflows Definition by id
PARAMETERS
	 
RETURNS: 
	A workflows definition

# Test Cases
 * [x] **Get a Workflow Definition by id (Success)**
```
GIVEN 
  Client is connected
  AND activiti server is available
  AND workflows wf1 is available
WHEN 
  Client call function get workflow by id
THEN
  client gets wf1
```
 * [x] **Get Workflow Definition by id (Fails)**
```
GIVEN 
  Client is connected
  AND activiti server is available
  AND workflows wf1 is not available
WHEN 
  Client call function get workflow by id
THEN
  client gets null

**Comment by dfch** [comment]
@schefDev your commit message was wrongly formatted, you have to write "resolves <issue number>" for every issue.
Could you please check if this issue can be closed? and if we need to release something?

**Comment by trumpetchris** [comment]
Issue can be closed.
