### ISSUE TITLE
Methods for deployments

### ISSUE THREAD

**Issue by schefDev** [dfensgmbh/biz.dfch.CS.Activiti.Client#17]
### Methods for deployments

- [x] Get Deployment(s) (For details see [here](http://activiti.org/userguide/index.html#_list_of_deployments))
- [x] Create Deployment (For details see [here](http://activiti.org/userguide/index.html#_create_a_new_deployment))
- [x] Delete Deployment (For details see [here](http://activiti.org/userguide/index.html#_delete_a_deployment))

**Comment by trumpetchris** [comment]
Client is terweitert, Tests (Unit tests) sind angepasst.
Nun noch die PS Tests anpassen und erweitern (Eigene issues), dann brauchts ein neuer Cimi-Client-Release.

**Comment by rufer7** [comment]
@trumpetchris du meinst wohl einen neuen Activiti.Client release oder?

**Comment by trumpetchris** [comment]
Ich mache mich nun hinter PS-Tests und teste local. Allenfalls gibt es noch Änderungen. Gebe Bescheid, wenn ein neuer Release fällig ist.
