### ISSUE TITLE
Feature: Define public properties of Client

### ISSUE THREAD

**Issue by dfch** [dfensgmbh/biz.dfch.CS.Activiti.Client#8]
ServerURI - URI for activiti API
credential object - Credentials for authentication on activiti API
   - Username
   - Password

Time out - API call time out

**Comment by schefDev** [comment]
#ProcessEngine Class (public)

#Properties
ApplicationName // Get application name such as Worker#1
IsLoggedIn // Get login status true or false

#Constructors
ProcessEngine(Uri server, string applicationName)
ProcessEngine()

#Methods
Login(credential)
Login(username, password)
//see interface

#Remarks
RestClient instance embedded
