### ISSUE TITLE
Integrate HttpClient as the basis of this module

### ISSUE THREAD

**Issue by dfch** [dfensgmbh/biz.dfch.CS.Activiti.Client#9]
The basis for HTTP communication with Activiti should be the [`HttpClient`](https://msdn.microsoft.com/en-us/library/system.net.http.httpclient) class. 

For an actual implementation see the [`RestHelper`](https://github.com/dfch/biz.dfch.CS.Infoblox.Wapi/blob/master/biz.dfch.CS.Infoblox.Wapi/RestHelper.cs#L11) used in [biz.dfch.CS.Infoblox.Wapi](https://github.com/dfch/biz.dfch.CS.Infoblox.Wapi) and my article [HttpClient and how to use Headers, Content-Type and PostAsync](http://d-fens.ch/2014/04/12/httpclient-and-how-to-use-headers-content-type-and-postasync/).

Use the Wapi `RestHelper` as a guideline on how to model the the Activiti client.

**Comment by schefDev** [comment]
##Decision
Leave [] RestClient (Class) as it is (needs cleanup) or instead [] using biz.dfch.CS.Utilities.Rest.

**Comment by dfch** [comment]
@schefDev what is the status here? are you now using the client from CS.Utilities?
can this issue be closed?

**Comment by schefDev** [comment]
fixed with commit https://github.com/dfensgmbh/biz.dfch.CS.Activiti.Client/commit/98a06da679fcddc1f8f6788e03596a4357e699f4
